import Head from 'next/head';
import React from 'react';

export default function HeadData() {
  return (
    <Head>
      <title>Luke Leckron - Web Developer</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
  );
}