'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import React, { useState } from 'react'
import MenuModal from './menu-modal'
import { AnimatePresence } from "framer-motion"
import Header from './header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Luke Leckron - Web Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [showMenuModal, setShowMenuModal] = useState(false)

  return (
    <html lang="en">
      <body>
        <Header showMenuModal={ showMenuModal } setShowMenuModal={ setShowMenuModal }/>
        {children}
        <AnimatePresence>
          {showMenuModal && <MenuModal showMenuModal={ showMenuModal } setShowMenuModal={ setShowMenuModal }/>}
        </AnimatePresence>
      </body>
    </html>
  )
}
